# Generated by Django 3.2 on 2022-04-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionewsapp', '0002_auto_20220420_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='original_website',
            new_name='original_news_link',
        ),
    ]
