# Generated by Django 3.2 on 2022-04-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionewsapp', '0003_rename_original_website_post_original_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='original_news_link',
            field=models.URLField(),
        ),
    ]
