# Generated by Django 3.2 on 2022-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionewsapp', '0004_alter_post_original_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='original_news_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
