# Generated by Django 3.2 on 2022-04-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionewsapp', '0005_alter_post_original_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='original_news_link',
            field=models.URLField(null=True),
        ),
    ]
